# Server Settings
server:
  port: 8094

# Eureka Settings
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Logging Settings
logging:
  level:
    root: INFO
    com.gsacm: DEBUG
  file: classpath:logs/club-service/file.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] %-5level %logger{36} - %msg%n"
# Spring Boot Settings
spring:
  output:
    ansi:
      enabled: always
  # DataSource
  datasource:
    url: jdbc:postgresql://localhost:5432/club_db
    username: admin
    password: admin
    jpa:
      hibernate:
        ddl-auto: none
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          show-sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          jdbc:
            batch_size: 50
          cache:
            use_second_level_cache: true
            region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          default_batch_fetch_size: 100
          generate_statistics: true
# Flyway Settings
flyway:
  locations: classpath:db/migration
  baselineOnMigrate: true
  validateOnMigrate: true


# Actuator Settings
management:
  tracing:
    sampling:
      probability: 1.0
  # Zipkin Settings
#  tracing:
#    # Configure Zipkin
#    zipkin:
#      enabled: true
#      base-url: http://localhost:9411 # Replace with your Zipkin server URL

# OpenAPI Settings
openapi:
  service:
    title: club-service doc
    version: 1.0.0
    url: http://localhost:8091
springdoc:
  api-docs:
    path: /club-service/v3/api-docs
  swagger-ui:
    path: /club-service/swagger-ui.html
