# Server Settings
server:
  port: 8094
  servlet:
    ## MULTIPART (MultipartProperties)
    multipart:
      # Enable multipart uploads
      enable: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: ../gsacm-platform/assets/images
  default-dir: ../gsacm-platform/assets/placeholder

# Eureka Settings
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Logging Settings
logging:
  level:
    root: INFO
    com.gsacm: DEBUG
  file: classpath:logs/club-service/file.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] %-5level %logger{36} - %msg%n"
# Spring Boot Settings
spring:
  output:
    ansi:
      enabled: always
  # DataSource
  datasource:
    url: jdbc:postgresql://localhost:5432/club_db
    username: admin
    password: admin
    jpa:
      hibernate:
        ddl-auto: none
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          show-sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
# Flyway Settings
flyway:
  locations: classpath:db/migration
  baselineOnMigrate: true
  validateOnMigrate: true


# Actuator Settings
management:
  tracing:
    sampling:
      probability: 1.0

# OpenAPI Settings
openapi:
  service:
    title: club-service doc
    version: 1.0.0
    url: http://localhost:8091
springdoc:
  api-docs:
    path: /club-service/v3/api-docs
  swagger-ui:
    path: /club-service/swagger-ui.html
