# Spring Settings
spring:
  application:
    name: club-service
  config:
    import: "optional:configserver:http://localhost:8088/"


#  datasource:
#    url: jdbc:postgresql://localhost:5432/club_db
#    username: admin
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show-sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true