# Server Settings
server:
  port: 8091

# Eureka Settings
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Logging Settings
logging:
  level:
    root: INFO
    com.gsacm: DEBUG
  file: classpath:logs/api-gateway/file.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] %-5level %logger{36} - %msg%n"

# Spring API Gateway Settings
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: openapi
#          uri: http://localhost:${server.port}
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
#        - id: club-service-docs
#          uri: lb://CLUB-SERVICE
#          predicates:
#            - Path=/club-service/v3/api-docs/**
#        - id: club-service
#          uri: lb://CLUB-SERVICE
#          predicates:
#            - Path=/api/v1/clubs/**

# Spring Doc Settings
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /club-service/v3/api-docs
        name: Club Service
        primaryName: Club Service


# Actuator Settings
management:
  metrics:
    export:
      # Enable Micrometer integration with Zipkin
      tracing:
        enabled: true
  # Zipkin Settings
  tracing:
    # Configure Zipkin
    zipkin:
      enabled: true
      base-url: http://localhost:9411 # Replace with your Zipkin server URL

