# Server Settings
server:
  port: 8091
# Eureka Settings
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

#Spring API Gateway Settings
spring:
  cloud:
    gateway:
      routes:
        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/v1/clubs/**
# Actuator Settings
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
