# Server Settings
server:
  port: 8096
# Eureka Settings
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Actuator Settings
management:
  tracing:
    sampling:
      probability: 1.0
  # Zipkin Settings
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans