# Spring Settings
spring:
  application:
    name: federation-service
  config:
    import: "optional:configserver:http://localhost:8088"

  #  DataSource
  datasource:
    url: jdbc:postgresql://localhost:5432/federation_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true




