# Server Settings
server:
  port: 8088
# spring Settings
spring:
  profiles:
    active: native
  application:
    name: cloud-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
